---
name: commitlint

on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Run npm install
        run: npm install

      - name: Run commitlint
        run: node node_modules/@commitlint/cli/cli.js --from=origin/main
